#! /bin/sh

prefix="/usr"
version="5.0.5"
includedir="/include/php"
includes="-I$includedir -I$includedir/main -I$includedir/TSRM -I$includedir/Zend"
ldflags=""
libs="-lcrypt   -lcrypt -lm  -lcrypt -lcrypt "
extension_dir='/lib/extensions/no-debug-non-zts-20041030'

case "$1" in
--prefix)
	echo $prefix;;
--includes)
	echo $includes;;
--ldflags)
	echo $ldflags;;
--libs)
	echo $libs;;
--extension-dir)
	echo $extension_dir;;
--version)
	echo $version;;
*)
	echo "Usage: $0 [--prefix|--includes|--ldflags|--libs|--extension-dir|--version]"
	exit 1;;
esac

exit 0
