u-boot.build/board/ruby/start.o: board/ruby/start.S include/config.h \
  include/configs/ruby_mini.h ../common/common_mem.h \
  ../common/ruby_config.h ../common/topaz_config.h \
  ../common/current_platform.h ../common/ruby_partitions.h \
  include/asm/config.h include/asm/arcregs.h include/asm/arch/platform.h \
  ../common/ruby_platform.h ../common/ruby_version.h \
  ../common/topaz_config.h ../common/uboot_header.h \
  include/timestamp_autogenerated.h board/ruby/start.inl

include/config.h:

include/configs/ruby_mini.h:

../common/common_mem.h:

../common/ruby_config.h:

../common/topaz_config.h:

../common/current_platform.h:

../common/ruby_partitions.h:

include/asm/config.h:

include/asm/arcregs.h:

include/asm/arch/platform.h:

../common/ruby_platform.h:

../common/ruby_version.h:

../common/topaz_config.h:

../common/uboot_header.h:

include/timestamp_autogenerated.h:

board/ruby/start.inl:
