build_mini/board/ruby/start.o: board/ruby/start.S \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/config.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/configs/ruby_mini.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/common_mem.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_config.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/topaz_config.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/current_platform.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_partitions.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/config.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/arcregs.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/arch/platform.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_platform.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_version.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/topaz_config.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/uboot_header.h \
  /home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/timestamp_autogenerated.h \
  board/ruby/start.inl

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/config.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/configs/ruby_mini.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/common_mem.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_config.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/topaz_config.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/current_platform.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_partitions.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/config.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/arcregs.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/asm/arch/platform.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_platform.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/ruby_version.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/topaz_config.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/../common/uboot_header.h:

/home/osboxes/AirTies4641_Sandbox/Quantenna-GPL/u-boot-2009.06/include/timestamp_autogenerated.h:

board/ruby/start.inl:
